### ISSUE TITLE
[ Bug ] - Read Article List API Error

### ISSUE THREAD

**Issue by kurtyoon** [CSID-DGU/2024-2-DSCD-talkingPotato-1#54]
## 🛠️ 발견된 버그 기능
[//]: # (어떤 부분에서 버그가 나오는지 적습니다.)

Article을 조회할 때 에러가 발생합니다.

## 🌎 발견된 환경
[//]: # (어떤 환경에서 버그가 나오는지 적습니다.)

Article을 조회할 때 Substring의 제약조건으로 인해 버그가 발생합니다.

## 📝 check-lists
- [x] Read Article List API Error

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the ArticleRepository to use GROUP_CONCAT with SUBSTRING to limit the length of concatenated tags, preventing potential errors due to substring constraints.

You can review changes in this commit: https://github.com/mnmnk43434/CSID-DGU-2024-2-DSCD-talkingPotato-1-54/commit/c3ba61733c77174e46b408575d36d0a856e5494d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
